language: bash
sudo: required
services:
  - docker

env:
  - VERSION=0.8.0
  - VERSION=0.8.1
  - VERSION=0.8.2
  - VERSION=0.8.3
  - VERSION=0.8.4
  - VERSION=0.8.5
  - VERSION=0.8.6
  - VERSION=0.9.0
  - VERSION=0.9.1
  - VERSION=0.9.2
  - VERSION=0.9.3
  - VERSION=0.9.4
  - VERSION=1.0.0
  - VERSION=1.0.1
  - VERSION=edge
matrix:
  exclude:
    - evn: VERSION=0.8.0 TRAVIS_EVENT_TYPE=cron
    - evn: VERSION=0.8.1 TRAVIS_EVENT_TYPE=cron
    - evn: VERSION=0.8.2 TRAVIS_EVENT_TYPE=cron
    - evn: VERSION=0.8.3 TRAVIS_EVENT_TYPE=cron
    - evn: VERSION=0.8.4 TRAVIS_EVENT_TYPE=cron
    - evn: VERSION=0.8.5 TRAVIS_EVENT_TYPE=cron
    - evn: VERSION=0.8.6 TRAVIS_EVENT_TYPE=cron
    - evn: VERSION=0.9.0 TRAVIS_EVENT_TYPE=cron
    - evn: VERSION=0.9.1 TRAVIS_EVENT_TYPE=cron
    - evn: VERSION=0.9.2 TRAVIS_EVENT_TYPE=cron
    - evn: VERSION=0.9.3 TRAVIS_EVENT_TYPE=cron
    - evn: VERSION=0.9.4 TRAVIS_EVENT_TYPE=cron
    - evn: VERSION=1.0.0 TRAVIS_EVENT_TYPE=cron
    - evn: VERSION=1.0.1 TRAVIS_EVENT_TYPE=cron
  allow_failures:
    - env: VERSION=edge

script:
  - ./build versions/$VERSION/options
  - ./build test versions/$VERSION/options

deploy:
  - provider: script
    script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && ./build push versions/$VERSION/options
    on:
      branch: master
