language: bash
sudo: required
services:
  - docker
script:
  - ./build versions/edge/options
after_success:
  - ./build test versions/edge/options
deploy:
  provider: script
  script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && ./build push versions/edge/options
  on:
    branch: master
